name: Machine Learning Model CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  ml_training:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 scikit-learn==1.5.2 pandas==2.2.3 numpy==1.26.4 matplotlib==3.9.2 seaborn==0.13.2

    - name: Run MLflow Project Experiment
      env:
        FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        # Menggunakan kredensial bawaan HTTP Basic Auth milik MLflow
        MLFLOW_TRACKING_USERNAME: "upan55678"
        MLFLOW_TRACKING_PASSWORD: "masukkan_token_panjang_dagshub_anda_di_sini"
      run: |
        mlflow run MLProject --entry-point main --env-manager local
